spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/crazy_task_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update
